source 'http://rubygems.org'

gem 'rake', '0.9.2.2'
gem 'rails', '3.0.9'
gem 'devise', '1.3.4'
gem 'jquery-rails', '1.0.9'
gem 'mysql', '2.8.1'
gem 'rcov', '0.9.9'
gem 'rspec-rails', '2.7.0'
gem 'formtastic'
gem 'haml'
gem 'haml-rails'
gem 'authlogic', '3.0.3'
gem 'fastercsv'
gem 'cancan'
gem 'csv_builder'
gem 'wicked_pdf'
group :development do 
  gem 'erb2haml'
end