development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: alfa_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: alfa_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: alfa_production
  pool: 5
  username: root
  password:

