require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LectureDaysController do

  # This should return the minimal set of attributes required to create a valid
  # LectureDay. As you add validations to LectureDay, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all lecture_days as @lecture_days" do
      lecture_day = LectureDay.create! valid_attributes
      get :index
      assigns(:lecture_days).should eq([lecture_day])
    end
  end

  describe "GET show" do
    it "assigns the requested lecture_day as @lecture_day" do
      lecture_day = LectureDay.create! valid_attributes
      get :show, :id => lecture_day.id
      assigns(:lecture_day).should eq(lecture_day)
    end
  end

  describe "GET new" do
    it "assigns a new lecture_day as @lecture_day" do
      get :new
      assigns(:lecture_day).should be_a_new(LectureDay)
    end
  end

  describe "GET edit" do
    it "assigns the requested lecture_day as @lecture_day" do
      lecture_day = LectureDay.create! valid_attributes
      get :edit, :id => lecture_day.id
      assigns(:lecture_day).should eq(lecture_day)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LectureDay" do
        expect {
          post :create, :lecture_day => valid_attributes
        }.to change(LectureDay, :count).by(1)
      end

      it "assigns a newly created lecture_day as @lecture_day" do
        post :create, :lecture_day => valid_attributes
        assigns(:lecture_day).should be_a(LectureDay)
        assigns(:lecture_day).should be_persisted
      end

      it "redirects to the created lecture_day" do
        post :create, :lecture_day => valid_attributes
        response.should redirect_to(LectureDay.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lecture_day as @lecture_day" do
        # Trigger the behavior that occurs when invalid params are submitted
        LectureDay.any_instance.stub(:save).and_return(false)
        post :create, :lecture_day => {}
        assigns(:lecture_day).should be_a_new(LectureDay)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LectureDay.any_instance.stub(:save).and_return(false)
        post :create, :lecture_day => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lecture_day" do
        lecture_day = LectureDay.create! valid_attributes
        # Assuming there are no other lecture_days in the database, this
        # specifies that the LectureDay created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LectureDay.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => lecture_day.id, :lecture_day => {'these' => 'params'}
      end

      it "assigns the requested lecture_day as @lecture_day" do
        lecture_day = LectureDay.create! valid_attributes
        put :update, :id => lecture_day.id, :lecture_day => valid_attributes
        assigns(:lecture_day).should eq(lecture_day)
      end

      it "redirects to the lecture_day" do
        lecture_day = LectureDay.create! valid_attributes
        put :update, :id => lecture_day.id, :lecture_day => valid_attributes
        response.should redirect_to(lecture_day)
      end
    end

    describe "with invalid params" do
      it "assigns the lecture_day as @lecture_day" do
        lecture_day = LectureDay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LectureDay.any_instance.stub(:save).and_return(false)
        put :update, :id => lecture_day.id, :lecture_day => {}
        assigns(:lecture_day).should eq(lecture_day)
      end

      it "re-renders the 'edit' template" do
        lecture_day = LectureDay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LectureDay.any_instance.stub(:save).and_return(false)
        put :update, :id => lecture_day.id, :lecture_day => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lecture_day" do
      lecture_day = LectureDay.create! valid_attributes
      expect {
        delete :destroy, :id => lecture_day.id
      }.to change(LectureDay, :count).by(-1)
    end

    it "redirects to the lecture_days list" do
      lecture_day = LectureDay.create! valid_attributes
      delete :destroy, :id => lecture_day.id
      response.should redirect_to(lecture_days_url)
    end
  end

end
