require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OccupationsController do

  # This should return the minimal set of attributes required to create a valid
  # Occupation. As you add validations to Occupation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all occupations as @occupations" do
      occupation = Occupation.create! valid_attributes
      get :index
      assigns(:occupations).should eq([occupation])
    end
  end

  describe "GET show" do
    it "assigns the requested occupation as @occupation" do
      occupation = Occupation.create! valid_attributes
      get :show, :id => occupation.id
      assigns(:occupation).should eq(occupation)
    end
  end

  describe "GET new" do
    it "assigns a new occupation as @occupation" do
      get :new
      assigns(:occupation).should be_a_new(Occupation)
    end
  end

  describe "GET edit" do
    it "assigns the requested occupation as @occupation" do
      occupation = Occupation.create! valid_attributes
      get :edit, :id => occupation.id
      assigns(:occupation).should eq(occupation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Occupation" do
        expect {
          post :create, :occupation => valid_attributes
        }.to change(Occupation, :count).by(1)
      end

      it "assigns a newly created occupation as @occupation" do
        post :create, :occupation => valid_attributes
        assigns(:occupation).should be_a(Occupation)
        assigns(:occupation).should be_persisted
      end

      it "redirects to the created occupation" do
        post :create, :occupation => valid_attributes
        response.should redirect_to(Occupation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved occupation as @occupation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Occupation.any_instance.stub(:save).and_return(false)
        post :create, :occupation => {}
        assigns(:occupation).should be_a_new(Occupation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Occupation.any_instance.stub(:save).and_return(false)
        post :create, :occupation => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested occupation" do
        occupation = Occupation.create! valid_attributes
        # Assuming there are no other occupations in the database, this
        # specifies that the Occupation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Occupation.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => occupation.id, :occupation => {'these' => 'params'}
      end

      it "assigns the requested occupation as @occupation" do
        occupation = Occupation.create! valid_attributes
        put :update, :id => occupation.id, :occupation => valid_attributes
        assigns(:occupation).should eq(occupation)
      end

      it "redirects to the occupation" do
        occupation = Occupation.create! valid_attributes
        put :update, :id => occupation.id, :occupation => valid_attributes
        response.should redirect_to(occupation)
      end
    end

    describe "with invalid params" do
      it "assigns the occupation as @occupation" do
        occupation = Occupation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Occupation.any_instance.stub(:save).and_return(false)
        put :update, :id => occupation.id, :occupation => {}
        assigns(:occupation).should eq(occupation)
      end

      it "re-renders the 'edit' template" do
        occupation = Occupation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Occupation.any_instance.stub(:save).and_return(false)
        put :update, :id => occupation.id, :occupation => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested occupation" do
      occupation = Occupation.create! valid_attributes
      expect {
        delete :destroy, :id => occupation.id
      }.to change(Occupation, :count).by(-1)
    end

    it "redirects to the occupations list" do
      occupation = Occupation.create! valid_attributes
      delete :destroy, :id => occupation.id
      response.should redirect_to(occupations_url)
    end
  end

end
