require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PhasesController do

  # This should return the minimal set of attributes required to create a valid
  # Phase. As you add validations to Phase, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all phases as @phases" do
      phase = Phase.create! valid_attributes
      get :index
      assigns(:phases).should eq([phase])
    end
  end

  describe "GET show" do
    it "assigns the requested phase as @phase" do
      phase = Phase.create! valid_attributes
      get :show, :id => phase.id
      assigns(:phase).should eq(phase)
    end
  end

  describe "GET new" do
    it "assigns a new phase as @phase" do
      get :new
      assigns(:phase).should be_a_new(Phase)
    end
  end

  describe "GET edit" do
    it "assigns the requested phase as @phase" do
      phase = Phase.create! valid_attributes
      get :edit, :id => phase.id
      assigns(:phase).should eq(phase)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Phase" do
        expect {
          post :create, :phase => valid_attributes
        }.to change(Phase, :count).by(1)
      end

      it "assigns a newly created phase as @phase" do
        post :create, :phase => valid_attributes
        assigns(:phase).should be_a(Phase)
        assigns(:phase).should be_persisted
      end

      it "redirects to the created phase" do
        post :create, :phase => valid_attributes
        response.should redirect_to(Phase.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved phase as @phase" do
        # Trigger the behavior that occurs when invalid params are submitted
        Phase.any_instance.stub(:save).and_return(false)
        post :create, :phase => {}
        assigns(:phase).should be_a_new(Phase)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Phase.any_instance.stub(:save).and_return(false)
        post :create, :phase => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested phase" do
        phase = Phase.create! valid_attributes
        # Assuming there are no other phases in the database, this
        # specifies that the Phase created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Phase.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => phase.id, :phase => {'these' => 'params'}
      end

      it "assigns the requested phase as @phase" do
        phase = Phase.create! valid_attributes
        put :update, :id => phase.id, :phase => valid_attributes
        assigns(:phase).should eq(phase)
      end

      it "redirects to the phase" do
        phase = Phase.create! valid_attributes
        put :update, :id => phase.id, :phase => valid_attributes
        response.should redirect_to(phase)
      end
    end

    describe "with invalid params" do
      it "assigns the phase as @phase" do
        phase = Phase.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Phase.any_instance.stub(:save).and_return(false)
        put :update, :id => phase.id, :phase => {}
        assigns(:phase).should eq(phase)
      end

      it "re-renders the 'edit' template" do
        phase = Phase.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Phase.any_instance.stub(:save).and_return(false)
        put :update, :id => phase.id, :phase => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested phase" do
      phase = Phase.create! valid_attributes
      expect {
        delete :destroy, :id => phase.id
      }.to change(Phase, :count).by(-1)
    end

    it "redirects to the phases list" do
      phase = Phase.create! valid_attributes
      delete :destroy, :id => phase.id
      response.should redirect_to(phases_url)
    end
  end

end
