require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RoomsController do

  # This should return the minimal set of attributes required to create a valid
  # Room. As you add validations to Room, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all rooms as @rooms" do
      room = Room.create! valid_attributes
      get :index
      assigns(:rooms).should eq([room])
    end
  end

  describe "GET show" do
    it "assigns the requested room as @room" do
      room = Room.create! valid_attributes
      get :show, :id => room.id.to_s
      assigns(:room).should eq(room)
    end
  end

  describe "GET new" do
    it "assigns a new room as @room" do
      get :new
      assigns(:room).should be_a_new(Room)
    end
  end

  describe "GET edit" do
    it "assigns the requested room as @room" do
      room = Room.create! valid_attributes
      get :edit, :id => room.id.to_s
      assigns(:room).should eq(room)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Room" do
        expect {
          post :create, :room => valid_attributes
        }.to change(Room, :count).by(1)
      end

      it "assigns a newly created room as @room" do
        post :create, :room => valid_attributes
        assigns(:room).should be_a(Room)
        assigns(:room).should be_persisted
      end

      it "redirects to the created room" do
        post :create, :room => valid_attributes
        response.should redirect_to(Room.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved room as @room" do
        # Trigger the behavior that occurs when invalid params are submitted
        Room.any_instance.stub(:save).and_return(false)
        post :create, :room => {}
        assigns(:room).should be_a_new(Room)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Room.any_instance.stub(:save).and_return(false)
        post :create, :room => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested room" do
        room = Room.create! valid_attributes
        # Assuming there are no other rooms in the database, this
        # specifies that the Room created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Room.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => room.id, :room => {'these' => 'params'}
      end

      it "assigns the requested room as @room" do
        room = Room.create! valid_attributes
        put :update, :id => room.id, :room => valid_attributes
        assigns(:room).should eq(room)
      end

      it "redirects to the room" do
        room = Room.create! valid_attributes
        put :update, :id => room.id, :room => valid_attributes
        response.should redirect_to(room)
      end
    end

    describe "with invalid params" do
      it "assigns the room as @room" do
        room = Room.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Room.any_instance.stub(:save).and_return(false)
        put :update, :id => room.id.to_s, :room => {}
        assigns(:room).should eq(room)
      end

      it "re-renders the 'edit' template" do
        room = Room.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Room.any_instance.stub(:save).and_return(false)
        put :update, :id => room.id.to_s, :room => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested room" do
      room = Room.create! valid_attributes
      expect {
        delete :destroy, :id => room.id.to_s
      }.to change(Room, :count).by(-1)
    end

    it "redirects to the rooms list" do
      room = Room.create! valid_attributes
      delete :destroy, :id => room.id.to_s
      response.should redirect_to(rooms_url)
    end
  end

end
