require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WorldReadingsController do

  # This should return the minimal set of attributes required to create a valid
  # WorldReading. As you add validations to WorldReading, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all world_readings as @world_readings" do
      world_reading = WorldReading.create! valid_attributes
      get :index
      assigns(:world_readings).should eq([world_reading])
    end
  end

  describe "GET show" do
    it "assigns the requested world_reading as @world_reading" do
      world_reading = WorldReading.create! valid_attributes
      get :show, :id => world_reading.id.to_s
      assigns(:world_reading).should eq(world_reading)
    end
  end

  describe "GET new" do
    it "assigns a new world_reading as @world_reading" do
      get :new
      assigns(:world_reading).should be_a_new(WorldReading)
    end
  end

  describe "GET edit" do
    it "assigns the requested world_reading as @world_reading" do
      world_reading = WorldReading.create! valid_attributes
      get :edit, :id => world_reading.id.to_s
      assigns(:world_reading).should eq(world_reading)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WorldReading" do
        expect {
          post :create, :world_reading => valid_attributes
        }.to change(WorldReading, :count).by(1)
      end

      it "assigns a newly created world_reading as @world_reading" do
        post :create, :world_reading => valid_attributes
        assigns(:world_reading).should be_a(WorldReading)
        assigns(:world_reading).should be_persisted
      end

      it "redirects to the created world_reading" do
        post :create, :world_reading => valid_attributes
        response.should redirect_to(WorldReading.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved world_reading as @world_reading" do
        # Trigger the behavior that occurs when invalid params are submitted
        WorldReading.any_instance.stub(:save).and_return(false)
        post :create, :world_reading => {}
        assigns(:world_reading).should be_a_new(WorldReading)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WorldReading.any_instance.stub(:save).and_return(false)
        post :create, :world_reading => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested world_reading" do
        world_reading = WorldReading.create! valid_attributes
        # Assuming there are no other world_readings in the database, this
        # specifies that the WorldReading created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WorldReading.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => world_reading.id, :world_reading => {'these' => 'params'}
      end

      it "assigns the requested world_reading as @world_reading" do
        world_reading = WorldReading.create! valid_attributes
        put :update, :id => world_reading.id, :world_reading => valid_attributes
        assigns(:world_reading).should eq(world_reading)
      end

      it "redirects to the world_reading" do
        world_reading = WorldReading.create! valid_attributes
        put :update, :id => world_reading.id, :world_reading => valid_attributes
        response.should redirect_to(world_reading)
      end
    end

    describe "with invalid params" do
      it "assigns the world_reading as @world_reading" do
        world_reading = WorldReading.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WorldReading.any_instance.stub(:save).and_return(false)
        put :update, :id => world_reading.id.to_s, :world_reading => {}
        assigns(:world_reading).should eq(world_reading)
      end

      it "re-renders the 'edit' template" do
        world_reading = WorldReading.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WorldReading.any_instance.stub(:save).and_return(false)
        put :update, :id => world_reading.id.to_s, :world_reading => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested world_reading" do
      world_reading = WorldReading.create! valid_attributes
      expect {
        delete :destroy, :id => world_reading.id.to_s
      }.to change(WorldReading, :count).by(-1)
    end

    it "redirects to the world_readings list" do
      world_reading = WorldReading.create! valid_attributes
      delete :destroy, :id => world_reading.id.to_s
      response.should redirect_to(world_readings_url)
    end
  end

end
